#SCREEN
SCREEN_WIDTH = 1920 #1280
SCREEN_HEIGHT = 1080 #720

#PLAYER
PLAYER_RADIUS = 20
LINE_WIDTH = 4
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_LIVES = 3
PLAYER_BOOSTER = 5
PLAYER_BOOSTER_COOLDOWN = 10

#ASTEROID
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#SHOT
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

#SCORE
SCORE_PER_KILL = 100

